import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useT } from "@/lib/LanguageContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KeyRound, Loader2, Headset, ShieldAlert } from "lucide-react";

export default function DiagnosticsGate({ onUnlock }) {
  const T = useT();
  const [code, setCode] = useState("");
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState("");

  const handleUnlock = async () => {
    setVerifying(true);
    setError("");
    try {
      const res = await base44.functions.invoke("verifyDiagnosticCode", { code });
      if (res.data?.valid) {
        onUnlock();
      } else {
        setError(res.data?.error || T("invalidDiagnosticCode", "Invalid or expired code."));
      }
    } catch (err) {
      setError(err.message || T("verificationFailed", "Verification failed."));
    } finally {
      setVerifying(false);
    }
  };

  return (
    <div className="bg-card rounded-xl shadow-sm border border-border p-6">
      {/* Header */}
      <div className="border-b border-border pb-4 mb-5">
        <h2 className="text-2xl font-bold font-heading text-foreground flex items-center gap-2">
          <Headset className="w-6 h-6 text-primary" /> {T("diagnosticsConsole", "Diagnostics Console")}
        </h2>
        <p className="text-muted-foreground text-sm mt-2">
          {T("consoleDescNew", "Enter the one-time diagnostic code provided by Rayma AI support to unlock the scan, repair, and security audit tools.")}
        </p>
      </div>

      {/* Code Entry */}
      <div className="text-center bg-primary/5 rounded-xl p-6 border border-primary/20 mb-4">
        <h3 className="text-base font-semibold text-foreground mb-2 flex items-center justify-center gap-2">
          <KeyRound className="w-5 h-5 text-primary" /> {T("enterDiagnosticCode", "Enter Diagnostic Code")}
        </h3>
        <p className="text-sm text-muted-foreground mb-4">
          {T("diagnosticCodeDesc", "This code is single-use, expires in 30 minutes, and is generated by an admin for your session.")}
        </p>
        <div className="flex gap-2 max-w-sm mx-auto">
          <Input
            placeholder={T("codePlaceholder", "e.g. 482-913")}
            value={code}
            onChange={e => setCode(e.target.value)}
            disabled={verifying}
            className="text-base text-center tracking-widest font-mono"
            onKeyDown={e => e.key === "Enter" && code && handleUnlock()}
          />
          <Button onClick={handleUnlock} disabled={verifying || !code} className="shrink-0" size="default">
            {verifying ? <Loader2 className="w-5 h-5 animate-spin" /> : <KeyRound className="w-5 h-5" />}
          </Button>
        </div>
        {error && <p className="text-sm text-destructive mt-3">{error}</p>}
      </div>

      {/* Admin Supervision Notice */}
      <div className="bg-amber-500/5 border border-amber-400/20 rounded-lg p-4">
        <div className="flex gap-3">
          <ShieldAlert className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-foreground mb-1">
              {T("adminSupervisionRequired", "Admin Supervision Required")}
            </p>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {T("diagnosticCodeNotice", "This console is for guided troubleshooting only. The admin generates a one-time code for your session — you cannot generate your own. After the code is used or expires, access is revoked automatically. For Rayma Chat debug mode, a separate PIN + admin password is required directly in the chat.")}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}